MVC/Controllers/KliniklerController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Contexts;
using DataAccess.Entities;
using Business.Models;
using Business.Services;
using DataAccess.Results.Bases;

//Generated from Custom Template.
namespace MVC.Controllers
{
    public class KliniklerController : Controller
    {
        // TODO: Add service injections here
        private readonly IKlinikService _klinikService;

        public KliniklerController(IKlinikService klinikService)
        {
            _klinikService = klinikService;
        }

        // GET: Klinikler
        public IActionResult Index()
        {
            IEnumerable<KlinikModel> klinikler;
            klinikler = _klinikService.Query().ToList();

            //1. yöntem
            //List<KlinikModel> klinikList = _klinikService.Query().ToList(); // TODO: Add get collection service logic here
            //2. yöntem
            List<KlinikModel> klinikList = _klinikService.GetList();
            return View(klinikList);
        }


        //GET:Klinikler/GetJson
        public JsonResult GetJson()
        {
            var klinikler = _klinikService.Query().ToList();
            return Json(klinikler);
        }



        // GET: Klinikler/Details/5
        public IActionResult Details(int id)
        {
            //koşula göre bulduğu ilk kaydı döner,eğer kaydı bulamazsa exception fırlatır.
            //KlinikModel klinik = _klinikService.Query().First(k=>k.Id==id);
            //koşula göre bulduğu ilk kaydı döner,eğer kaydı bulamazsa null döner.
            //KlinikModel klinik = _klinikService.Query().FirstOrDefault(k => k.Id == id);
            //koşula göre bulduğu son kaydı döner,eğer kaydı bulamazsa exception fırlatır.
            //KlinikModel klinik = _klinikService.Query().Last(k => k.Id == id);
            //koşula göre bulduğu son kaydı döner,eğer kaydı bulamazsa null döner.
            //KlinikModel klinik = _klinikService.Query().LastOrDefault(k => k.Id == id);
            //koşula göre bulduğu tek kaydı döner,eğer kaydı bulamazsa exception fırlatır,birden çok kayıt bulursa exception fırlatır.
            //KlinikModel klinik = _klinikService.Query().Single(k => k.Id == id);

            //önce kayıtlar where ile filtrelenir , dönen koleksiyon sonucu üzerinden tek bir kayıt çekilir.
            //KlinikModel klinik = _klinikService.Query().Where(k => k.Id == id).SingleOrDefault();

            //1. yöntem
            KlinikModel klinik = _klinikService.GetItem(id);

            //2.yöntem
            //koşula göre bulduğu tek kaydı döner,eğer kaydı bulamazsa null döner,birden çok kayıt bulursa exception fırlatır.
            //KlinikModel klinik = _klinikService.Query().SingleOrDefault(k=>k.Id==id); // TODO: Add get item service logic here
            if (klinik == null)
            {
                return NotFound();//404(not faund) http status code
            }
            return View(klinik);// 200(ok) http status code
        }

        public IActionResult GetItemJson(int id)
        {
            var klinik = _klinikService.Query().SingleOrDefault(k => k.Id == id);
            return Json(klinik);
        }





        // GET: Klinikler/Create
        //[HttpGet] default get
        public IActionResult Create(string Adi,string Aciklamasi)
        {
            // TODO: Add get related items service logic here to set ViewData if necessary
            return View();
        }

        // POST: Klinikler/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(KlinikModel klinik)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add insert service logic here
                Result result = _klinikService.Add(klinik);
                if (result.IsSuccessful)
                {
                    TempData["Mesaj"] = result.Message;

                    //1. yöntem
                    //return RedirectToAction("Index");
                    //2. yöntem
                    //return RedirectToAction(nameof(Index));
                    //3. yöntem
                    return RedirectToAction(nameof(Details),new {id=klinik.Id});
				}

                //1. yöntem
                //ViewData["mesaj"] = result.Message;
                //2. YÖNTEM
                //ViewBag.Mesaj = result.Message;
                //3. YÖNTEM
                ModelState.AddModelError("",result.Message);//view -> validation summary
            }
            // TODO: Add get related items service logic here to set ViewData if necessary
            return View(klinik);
           
        }

        // GET: Klinikler/Edit/5
        public IActionResult Edit(int id)
        {
            KlinikModel klinik = _klinikService.Query().SingleOrDefault(k=>k.Id==id); // TODO: Add get item service logic here
            if (klinik == null)
            {
                return NotFound();
            }
            // TODO: Add get related items service logic here to set ViewData if necessary
            return View(klinik);
        }

        // POST: Klinikler/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(KlinikModel klinik)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add update service logic here
                Result result = _klinikService.Update(klinik);
                if (result.IsSuccessful)
                {
                    TempData["Mesaj"] = result.Message;
                    return RedirectToAction(nameof(Details),new {id=klinik.Id} );
                }
                ModelState.AddModelError("", result.Message);//view-> validation summary
            }
            // TODO: Add get related items service logic here to set ViewData if necessary
            return View(klinik);
        }

        // GET: Klinikler/Delete/5
        public IActionResult Delete(int id)
        {
            KlinikModel klinik = _klinikService.GetItem(id); // TODO: Add get item service logic here
            if (klinik == null)
            {
                return NotFound();
            }
            return View(klinik);
        }

        // POST: Klinikler/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // TODO: Add delete service logic here
            Result result=_klinikService.Delete(id);
            TempData["Mesaj"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
	}
}

MVC/Views/Klinikler/Create.cshtml
@model KlinikModel
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Yeni Klinik";
}

<h1>@ViewData["Title"]</h1>

@*1. yöntem*@
@* @if(ViewData["mesaj"] is not null)
{
	<p class="text-danger">@ViewData["mesaj"]</p>
} *@

@*2. yöntem: ViewData ile ViewBag aslında aynı yapı birbirlerinin yerine kullanılabilir*@ 
@* @if (ViewBag.Mesaj is not null)
{
	<p class="text-danger">@ViewBag.Mesaj</p>
} *@
@*3. yöntem:servis sonuç mesajını validation summary üzerinden gösteriyoruz  *@


<h4>Klinik</h4>
<hr />
<div class="row">
    <div class="col-12">
		@*HTML*@
		@*1. yöntem*@
		@*<form action="Klinikler/Create" method="get">*@
	    @*2. yöntem*@
		@*<form action="Klinikler/Create">@*default method:get*@
		@*default method:get*@
		@*3. yöntem*@
		@*<form action="Klinikler/Create" method="post">*@
		@*Tag helper*@
		@*1. yöntem*@
		@*<form asp-action="Create" asp-controller="Klinikler" method="post">*@
		@*2. yöntem*@
		<form asp-action="Create"></form>
		@*default method:post*@

		@*Html helper*@
		@*1. yöntem*@
		@* @using (Html.BeginForm("Create", "Klinikler", FormMethod.Post() *@
		@*2.yöntem*@
		@* @using (Html.BeginForm("Create")) @*default method:post*@ 
		@*default method:post*@
		@*3.yöntem*@
		@using (Html.BeginForm())
		{

		@Html.AntiForgeryToken()
		@* <div class="text-danger">modeldeki data annotation validasyon mesajları</div> *@
		@*HTML helper*@

		@*Tag helper*@
	    @*<div asp-validation-summary="All" class="text-danger"></div>*@
        @*HTML helper*@
		@Html.ValidationSummary(false,null,new {@class="text-danger"})

            <div class="row mb-3">

				@*HTML*@
				@* <label id="Adi" class="col-2 col-form-label">Adı</label> *@
				@*Tag Helper*@
                @*   <label asp-for="Adi" class="col-2 col-form-label"></label> *@
			    @*Html Helper*@
				@Html.LabelFor(model => model.Adi, new { @class = "col-2 col-form-label" })

				<div class="col-5">

					@*HTML*@
					@* <input type="text" name="Adi" class="form-control" id="Adi" /> *@
					@*Tag Helper*@
					@* <input asp-for="Adi" class="form-control" /> @*name="Adi"*@ 
					@*Html Helper*@
					@Html.TextBoxFor(model=>model.Adi,new{@class="form-control" })

					@*Html*@
					@* <span class="text-danger">modeldeki Adi özelliği için data annotation validasyon mesajı </span> *@
					@*Tag Helper*@
					@* <span asp-validation-for="Adi" class="text-danger"></span> *@
					@*Html Helper*@
					@Html.ValidationMessageFor(model=>model.Adi,null,new {@class="text-danger"})
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="Aciklamasi" class="col-2 col-form-label"></label>
				<div class="col-5">

					@*HTML*@
					@* <textarea name="Aciklamasi" id="Aciklamasi" class="form-control" rows="3"></textarea> *@
					@*Tag Helper*@
					@* <textarea asp-for="Aciklamasi" class="form-control" rows="3"></textarea> @*name="Aciklamasi"*@ 
					@*Html Helper*@
					@Html.TextAreaFor(model=>model.Aciklamasi,new {rows="3", @class="form-control"})
					
					<span asp-validation-for="Aciklamasi" class="text-danger"></span>
				</div>
            </div>
           
            <div class="row mb-3">
				<div class="offset-2 col-5">

					@*1. yöntem*@
					@*<input type="submit" value="Kaydet" class="btn btn-primary" />*@
					@*2.yöntem*@
					<button type="submit" class="btn btn-primary">Kaydet</button>

					&nbsp;&nbsp;
                    <button type="reset" class="btn btn-outline-primary">Temizle</button>
					&nbsp;&nbsp;
					<a asp-action="Index">Listeye Dön</a>
				</div>
            </div>
		@*  </form> *@
        }
      
    </div>
</div>
</div>

MVC/Views/Klinikler/Delete.cshtml
@model KlinikModel
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Klinik Sil";
}

<h1>@ViewData["Title"]</h1>

<h3>Kliniği silmek istediğinizden eminmisiniz?</h3>
<div>
    <h4>Klinik</h4>
    <hr />
    <dl class="row">
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Adi)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Adi)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Aciklamasi)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Aciklamasi)
        </dd>
       
    </dl>
    
    <form asp-action="Delete">
	@Html.AntiForgeryToken()
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Evet" class="btn btn-danger" />&nbsp;&nbsp;
        <a asp-action="Index" class="btn btn-success">Hayır</a>
    </form>
</div>

MVC/Views/Klinikler/Details.cshtml
@model KlinikModel
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Klinik Detayı";
}

<div class="container">

<h1>@ViewData["Title"]</h1>

    @if (TempData["Mesaj"] != null)
    {
        <p class="text-danger">@TempData["Mesaj"]</p>
    }

    <div>
    <h4>Klinik</h4>
    <hr />
        <dl class="row">
            <dt class="col-2">
                @Html.DisplayNameFor(model => model.Adi)
            </dt>
            <dd class="col-10">
                @Html.DisplayFor(model => model.Adi)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-2">
                @Html.DisplayNameFor(model => model.Aciklamasi)
            </dt>
            <dd class="col-10">
                @Html.DisplayFor(model => model.Aciklamasi)
            </dd>
        </dl>
        @if (Model.DoktorSayisiOutput > 0)
        {
            <dl class="row">
                <dt class="col-2">
                    @Html.DisplayNameFor(model => model.DoktorSayisiOutput)
                </dt>
                <dd class="col-10">
                    @Html.DisplayFor(model => model.DoktorSayisiOutput)
                </dd>
            </dl>
            <dl class="row">
                <dt class="col-2">
                    @Html.DisplayNameFor(model => model.DoktorlarOutput)
                </dt>
                <dd class="col-10">
                    @Html.Raw(Model.DoktorlarOutput)
                </dd>
            </dl>
        }

        <a asp-action="GetItemJson" asp-route-id="@Model.Id" target="_blank">Klinik JSON</a>

    </div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Düzenle</a>&nbsp;|&nbsp;
    <a asp-action="Index">Listeye dön</a>
</div>

</div>

MVC/Views/Klinikler/Edit.cshtml
@model KlinikModel
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Klinik Düzenle";
}

<h1>@ViewData["Title"]</h1>

<h4>Klinik</h4>
<hr />
<div class="row">
    <div class="col-12">
        <form asp-action="Edit">
		@Html.AntiForgeryToken()
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row mb-3">
                <label asp-for="Adi" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="Adi" class="form-control" />
					<span asp-validation-for="Adi" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="Aciklamasi" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="Aciklamasi" class="form-control" />
					<span asp-validation-for="Aciklamasi" class="text-danger"></span>
				</div>
            </div>
            <input type="hidden" asp-for="Id" />          
            <div class="row mb-3">
				<div class="offset-2 col-5">
					<input type="submit" value="Save" class="btn btn-primary" />
					&nbsp;&nbsp;
                    <button type="reset" class="btn btn-outline-primary">Temizle</button>
					&nbsp;&nbsp;
					<a asp-action="Index">Listeye Dön</a>
				</div>
            </div>
        </form>
    </div>
</div>
</div>

MVC/Views/Klinikler/Index.cshtml
@*1.yöntem*@
@*@model IEnumerable<Business.Models.KlinikModel>*@
@*2.yöntem*@

@*model List<KlinikModel>*@

@*3.yöntem*@

@model IEnumerable<KlinikModel>


@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Klinikler";
}

<div class="container">


<h1>@ViewData["Title"]</h1>


    @*details ekranına yönlendirildiği için burda kullanılmasına gerek yok*@
    @if (TempData["Mesaj"] != null)
    {
        <p class="text-danger">@TempData["Mesaj"]</p>
    }

<p>
    @*1.html*@
    @*<a href="/Klinikler/Create">Yeni Klinik</a>*@

    @*2.html helper*@
    @*1.yöntem*@
    @*@Html.ActionLink("Yeni Klinik","Create","Klinikler")*@
    @*2.yöntem*@
    @*Html.ActionLink("Yeni Klinik","Create")*@

    @*3. Tag helper*@
    @*1.yöntem*@
    @*<a asp-action="Create" asp-controller="Klinikler">Yeni Klinik</a>*@

    @*2.yöntem*@
    <a asp-action="Create">Yeni Klinik</a>

</p>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                @*1) html*@
                @*Adi*@
                @*2) html helper*@
                @Html.DisplayNameFor(model => model.Adi)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
		@foreach (var item in Model) {
				<tr>
					<td class="w-75">
                        @*1. yöntem*@
                        @* @item.Adi *@
                        @*2. yöntem*@
						@Html.DisplayFor(modelItem => item.Adi) @*model özelliğinin verisi*@
					</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DoktorSayisiOutput) 
                    </td>
					<td class="text-end">
                        @*1)html*@
                        @*<a href="/Klinikler/Details/@item.Id">Detay</a>*@
                        @*2)html helper*@
                        @*@Html.ActionLink("Detay","Details",new{id=item.Id})*@
                        @*3)Tag helper*@
						<a asp-action="Details" asp-route-id="@item.Id">Detay</a>&nbsp;|&nbsp;
						<a asp-action="Edit" asp-route-id="@item.Id">Düzenle</a>&nbsp;|&nbsp;
						<a asp-action="Delete" asp-route-id="@item.Id">Sil</a>
					</td>
				</tr>
		}
    </tbody>
</table>
<a asp-action="GetJson" target="_blank">Klinikler JSON</a>
</div>